MONGO_URI: mongodb://localhost:27017/products
AUTH_SERVER_URL: http://localhost:8070
AUTH_SERVER: localhost:8070

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG