server:
  port: 8080
  servlet:
    context-path: /products-service
spring:
  application:
    name: PRODUCTS-SERVICE
  profiles:
    active: ${ENV}
  data:
    mongodb:
      uri: ${MONGO_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL}
  actuator:
    health:
          show-details: always
          enabled: true
app:
  security:
    jwtSecret: kashdsakdhaisdhwqhdu323uhewdwiuedhwiehdwiwdeiuhdwiuhwsoiajdaoidjas


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health